using UnityEngine;
using UnityEngine.UI; // UI 관련라이브러리 (도구)
using TMPro; // textmeshpro 관련 라이브러리
using UnityEngine.SceneManagement;
using System.Diagnostics.Tracing;// 씬 관리 관련 라이브러리
public class GameManager : MonoBehaviour
{
    public GameObject gameoverText; // 게임오버시 활성화할 게임 오브젝트
    public TextMeshProUGUI timetext; //생존 시간을 표시할 텍스트 컴포넌트
    public TextMeshProUGUI recordText; // 최고 기록을 표시할 텍스트 컴포넌트

    private float surviveTime; // 생존시간
    private bool isGameover;//게임오버 상태
    void Start()
    {
        // 생존시간과 게임오버 상태 초기화
        surviveTime = 0f;
        isGameover = false;
    }


    void Update()
    {
        // 게임오버가 아닌동안

        if (!isGameover)
        {
            // 생존시간 갱신
            surviveTime += Time.deltaTime;
            // 갱신한 생존 시간을 timeText  텍스트를 컴포넌트를 통해 표시
            timetext.text = "Time : " + (int)surviveTime;
        }
        else
        {
            // 게임오버 상태에서 R키를 누르면 {
            if (Input.GetKeyDown(KeyCode.R))
            {
                //sample scene 씬을 로드
                SceneManager.LoadScene("MainGame");
            }
        }


    }

    //현재 게임을 게임오버 상태로 변경하는 메서드
    public void EndGame()
    {
        // 현재 상태를 게임오버 상태로 전환
        isGameover = true;
        //게임오버 텍스트 게임오브젝트를 활성화
        gameoverText.SetActive(true);


        //bestTime 키로 저장괸 이전까지의 최고 기록 가져오기
        float bestTime = PlayerPrefs.GetFloat("BestTime");

        //이전까지의 최고 기록보다 현재 생존시간이 더 크다면
        if (surviveTime > bestTime)
        {
            //최고 기록 값을 현재 생존 시간 값으로변경
            bestTime = surviveTime;

            // 변경된 최고 기록을 BestTime 키로 저장
            PlayerPrefs.SetFloat("BestTime", bestTime);
        }
        // 최고 기록ㅇ르 recordText 텍스트 컴포넌트를 통해 표시
        recordText.text = "Best Time" + (int)bestTime;
    }
}
